-- 01_creacion_tablas.sql
-- Proyecto Final - Bases de Datos 1
-- Sistema de Base de Conocimientos para Triage en Urgencias (SBCTU)
-- Crea la base de datos y todas las tablas principales
-- Motor: MySQL (Workbench 8.0+)

-- Elimina la base si ya existe y crea una nueva
DROP DATABASE IF EXISTS SBCTU;
CREATE DATABASE SBCTU CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE SBCTU;

-- TABLA: PACIENTE
-- Guarda la información personal y de contacto
CREATE TABLE PACIENTE (
  ID_PACIENTE INT AUTO_INCREMENT PRIMARY KEY,
  PRIMER_NOMBRE VARCHAR(15) NOT NULL,
  SEGUNDO_NOMBRE VARCHAR(15),
  PRIMER_APELLIDO VARCHAR(15) NOT NULL,
  SEGUNDO_APELLIDO VARCHAR(15),
  FECHA_NACIMIENTO DATE NOT NULL,
  GENERO CHAR(1) NOT NULL,
  DIRECCION VARCHAR(50),
  CORREO VARCHAR(100) NOT NULL UNIQUE
);

-- TABLA: PERSONAL_MEDICO
-- Médicos o enfermeros que realizan triages y diagnósticos
CREATE TABLE PERSONAL_MEDICO (
  ID_PERSONAL INT AUTO_INCREMENT PRIMARY KEY,
  PRIMER_NOMBRE VARCHAR(15) NOT NULL,
  SEGUNDO_NOMBRE VARCHAR(15),
  PRIMER_APELLIDO VARCHAR(15) NOT NULL,
  SEGUNDO_APELLIDO VARCHAR(15),
  NUMERO_LICENCIA VARCHAR(30) NOT NULL UNIQUE,
  CARGO VARCHAR(20) NOT NULL,
  CORREO_INSTITUCIONAL VARCHAR(100) NOT NULL UNIQUE
);

-- TABLA: NIVEL_URGENCIA
-- Define la prioridad de atención (1 Crítico - 4 Leve)
CREATE TABLE NIVEL_URGENCIA (
  ID_NIVEL_URGENCIA INT AUTO_INCREMENT PRIMARY KEY,
  CODIGO_NIVEL TINYINT NOT NULL UNIQUE,
  DESCRIPCION VARCHAR(30) NOT NULL
);

-- TABLA: ENFERMEDAD
-- Registra las enfermedades conocidas en la base de conocimiento
CREATE TABLE ENFERMEDAD (
  ID_ENFERMEDAD INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE_ENFERMEDAD VARCHAR(50) NOT NULL,
  DESCRIPCION VARCHAR(100),
  CODIGO_ENFERMEDAD INT NOT NULL UNIQUE,
  TRATAMIENTO VARCHAR(100),
  OBSERVACIONES VARCHAR(100),
  CATEGORIA VARCHAR(30) NOT NULL
);

-- TABLA: SINTOMA
-- Lista de síntomas observados en los pacientes
CREATE TABLE SINTOMA (
  ID_SINTOMA INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE_SINTOMA VARCHAR(100) NOT NULL,
  DESCRIPCION VARCHAR(100)
);

-- TABLA: ENFERMEDAD_SINTOMA
-- Relación muchos a muchos entre enfermedades y síntomas
CREATE TABLE ENFERMEDAD_SINTOMA (
  SINTOMA_ID_SINTOMA INT NOT NULL,
  ENFERMEDAD_ID_ENFERMEDAD INT NOT NULL,
  PRIMARY KEY (SINTOMA_ID_SINTOMA, ENFERMEDAD_ID_ENFERMEDAD),
  CONSTRAINT FK_ENF_SIN_SINTOMA FOREIGN KEY (SINTOMA_ID_SINTOMA) REFERENCES SINTOMA(ID_SINTOMA),
  CONSTRAINT FK_ENF_SIN_ENFERMEDAD FOREIGN KEY (ENFERMEDAD_ID_ENFERMEDAD) REFERENCES ENFERMEDAD(ID_ENFERMEDAD)
);

-- TABLA: VISITA
-- Cada ingreso de un paciente al área de urgencias
CREATE TABLE VISITA (
  ID_VISITA INT AUTO_INCREMENT PRIMARY KEY,
  FECHA_VISITA DATE NOT NULL,
  HORA_VISITA TIME NOT NULL,
  MOTIVO_CONSULTA VARCHAR(200) NOT NULL,
  ESTADO_VISITA VARCHAR(20) NOT NULL,
  PACIENTE_ID_PACIENTE INT NOT NULL,
  TRIAGE_ID_TRIAGE INT NULL,
  CONSTRAINT FK_VISITA_PACIENTE FOREIGN KEY (PACIENTE_ID_PACIENTE)
    REFERENCES PACIENTE(ID_PACIENTE)
);

-- TABLA: TRIAGE
-- Evaluación inicial realizada al paciente
CREATE TABLE TRIAGE (
  ID_TRIAGE INT AUTO_INCREMENT PRIMARY KEY,
  OBSERVACIONES VARCHAR(100) NOT NULL,
  CONSTANTES_VITALES VARCHAR(100) NOT NULL,
  HORA_ATENCION TIME NOT NULL,
  VISITA_ID_VISITA INT NOT NULL,
  PERSONAL_MEDICO_ID_PERSONAL INT NOT NULL,
  NIVEL_URGENCIA_ID_NIVEL_URGENCIA INT NOT NULL,
  CONSTRAINT FK_TRIAGE_VISITA FOREIGN KEY (VISITA_ID_VISITA) REFERENCES VISITA(ID_VISITA),
  CONSTRAINT FK_TRIAGE_PERSONAL FOREIGN KEY (PERSONAL_MEDICO_ID_PERSONAL) REFERENCES PERSONAL_MEDICO(ID_PERSONAL),
  CONSTRAINT FK_TRIAGE_NIVEL FOREIGN KEY (NIVEL_URGENCIA_ID_NIVEL_URGENCIA) REFERENCES NIVEL_URGENCIA(ID_NIVEL_URGENCIA)
);

-- CLAVE FORÁNEA CRUZADA VISITA–TRIAGE
-- Se agrega después para evitar errores de referencia circular
ALTER TABLE VISITA
ADD CONSTRAINT FK_VISITA_TRIAGE
FOREIGN KEY (TRIAGE_ID_TRIAGE)
REFERENCES TRIAGE(ID_TRIAGE);

-- TABLA: TRIAGE_SINTOMA
-- Relaciona los síntomas observados durante un triage
CREATE TABLE TRIAGE_SINTOMA (
  TRIAGE_ID_TRIAGE INT NOT NULL,
  SINTOMA_ID_SINTOMA INT NOT NULL,
  PRIMARY KEY (TRIAGE_ID_TRIAGE, SINTOMA_ID_SINTOMA),
  CONSTRAINT FK_TRIAGE_SINTOMA_TRIAGE FOREIGN KEY (TRIAGE_ID_TRIAGE) REFERENCES TRIAGE(ID_TRIAGE),
  CONSTRAINT FK_TRIAGE_SINTOMA_SINTOMA FOREIGN KEY (SINTOMA_ID_SINTOMA) REFERENCES SINTOMA(ID_SINTOMA)
);

-- TABLA: DIAGNOSTICO
-- Resultado médico emitido tras la evaluación
CREATE TABLE DIAGNOSTICO (
  ID_DIAGNOSTICO INT AUTO_INCREMENT PRIMARY KEY,
  FECHA_DIAGNOSTICO DATE NOT NULL,
  TIPO_DIAGNOSTICO VARCHAR(20) NOT NULL,
  OBSERVACIONES VARCHAR(100),
  ENFERMEDAD_ID_ENFERMEDAD INT NOT NULL,
  TRIAGE_ID_TRIAGE INT NOT NULL,
  PERSONAL_MEDICO_ID_PERSONAL INT NOT NULL,
  NIVEL_URGENCIA_ID_NIVEL_URGENCIA INT NOT NULL,
  CONSTRAINT FK_DIAG_ENFERMEDAD FOREIGN KEY (ENFERMEDAD_ID_ENFERMEDAD) REFERENCES ENFERMEDAD(ID_ENFERMEDAD),
  CONSTRAINT FK_DIAG_TRIAGE FOREIGN KEY (TRIAGE_ID_TRIAGE) REFERENCES TRIAGE(ID_TRIAGE),
  CONSTRAINT FK_DIAG_PERSONAL FOREIGN KEY (PERSONAL_MEDICO_ID_PERSONAL) REFERENCES PERSONAL_MEDICO(ID_PERSONAL),
  CONSTRAINT FK_DIAG_NIVEL FOREIGN KEY (NIVEL_URGENCIA_ID_NIVEL_URGENCIA) REFERENCES NIVEL_URGENCIA(ID_NIVEL_URGENCIA)
);