-- 02_insercion_datos.sql
-- Inserta datos de ejemplo para el sistema SBCTU
USE SBCTU;

-- PACIENTES
INSERT INTO PACIENTE (PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, FECHA_NACIMIENTO, GENERO, DIRECCION, CORREO)
VALUES
('JUAN','CARLOS','PEREZ','GOMEZ','1988-04-12','M','CRA 10 #20-30','juan.perez@example.com'),
('ANA',NULL,'LOPEZ','MARTINEZ','1995-11-03','F','CALLE 45 #12-34','ana.lopez@example.com');

-- PERSONALES MEDICOS
INSERT INTO PERSONAL_MEDICO (PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, NUMERO_LICENCIA, CARGO, CORREO_INSTITUCIONAL)
VALUES
('LAURA','MARIA','RODRIGUEZ','HERNANDEZ','LIC-12345','MEDICO','laura.rodriguez@hospital.org'),
('MIGUEL',NULL,'SUAREZ','PARDO','LIC-98765','ENFERMERO','miguel.suarez@hospital.org');

-- NIVEL DE URGENCIA
INSERT INTO NIVEL_URGENCIA (CODIGO_NIVEL, DESCRIPCION) VALUES
(1,'CRITICO'),(2,'GRAVE'),(3,'MODERADO'),(4,'LEVE');

-- ENFERMEDAD
INSERT INTO ENFERMEDAD (NOMBRE_ENFERMEDAD, DESCRIPCION, CODIGO_ENFERMEDAD, TRATAMIENTO, CATEGORIA) VALUES
('NEUMONIA','INFECCION PULMONAR',10001,'ANTIBIOTICOS Y REPOSO','RESPIRATORIA'),
('GASTROENTERITIS','INFLAMACION GASTROINTESTINAL',20001,'HIDRATACION Y DIETA','INFECCIOSA');

-- SINTOMA
INSERT INTO SINTOMA (NOMBRE_SINTOMA, DESCRIPCION) VALUES
('FIEBRE','TEMPERATURA MAYOR A 38°C'),
('TOS PERSISTENTE','TOS POR MAS DE 2 SEMANAS'),
('DOLOR ABDOMINAL','DOLOR LOCALIZADO EN EL ABDOMEN');

-- ENFERMEDAD - SINTOMA
INSERT INTO ENFERMEDAD_SINTOMA VALUES (1,1),(2,1),(1,2),(3,2);

-- VISITA
INSERT INTO VISITA (FECHA_VISITA, HORA_VISITA, MOTIVO_CONSULTA, ESTADO_VISITA, PACIENTE_ID_PACIENTE)
VALUES
(CURDATE(),'08:30:00','FIEBRE Y TOS','ATENCION',1),
(CURDATE(),'09:15:00','DOLOR ABDOMINAL','ATENCION',2);

-- TRIAGE
INSERT INTO TRIAGE (OBSERVACIONES, CONSTANTES_VITALES, HORA_ATENCION, VISITA_ID_VISITA, PERSONAL_MEDICO_ID_PERSONAL, NIVEL_URGENCIA_ID_NIVEL_URGENCIA)
VALUES
('PACIENTE CON DISNEA LEVE','TA 120/80 TEMP 38.5 FC 95','08:45:00',1,1,2),
('DOLOR MODERADO E HIDRATADO','TA 110/70 TEMP 37.8 FC 88','09:30:00',2,2,3);

-- TRIAGE - SINTOMA
INSERT INTO TRIAGE_SINTOMA VALUES (1,1),(1,2),(2,3);

-- DIAGNOSTICO
INSERT INTO DIAGNOSTICO (FECHA_DIAGNOSTICO, TIPO_DIAGNOSTICO, OBSERVACIONES, ENFERMEDAD_ID_ENFERMEDAD, TRIAGE_ID_TRIAGE, PERSONAL_MEDICO_ID_PERSONAL, NIVEL_URGENCIA_ID_NIVEL_URGENCIA)
VALUES
(CURDATE(),'PRELIMINAR','SOSPECHA DE NEUMONIA',1,1,1,2),
(CURDATE(),'CONFIRMADO','CUADRO COMPATIBLE CON GASTROENTERITIS',2,2,2,3);