-- 03_vistas_y_triggers.sql
-- Contiene vistas, procedimientos y triggers del sistema SBCTU
USE SBCTU;

-- VISTA: HISTORIAL CLÍNICO COMPLETO DE CADA PACIENTE
CREATE OR REPLACE VIEW VW_HISTORIAL_PACIENTE AS
SELECT P.ID_PACIENTE, CONCAT(P.PRIMER_APELLIDO,' ',P.PRIMER_NOMBRE) AS PACIENTE,
V.FECHA_VISITA, T.OBSERVACIONES, D.TIPO_DIAGNOSTICO, E.NOMBRE_ENFERMEDAD, N.DESCRIPCION AS NIVEL
FROM PACIENTE P
JOIN VISITA V ON V.PACIENTE_ID_PACIENTE = P.ID_PACIENTE
LEFT JOIN TRIAGE T ON T.VISITA_ID_VISITA = V.ID_VISITA
LEFT JOIN DIAGNOSTICO D ON D.TRIAGE_ID_TRIAGE = T.ID_TRIAGE
LEFT JOIN ENFERMEDAD E ON E.ID_ENFERMEDAD = D.ENFERMEDAD_ID_ENFERMEDAD
LEFT JOIN NIVEL_URGENCIA N ON N.ID_NIVEL_URGENCIA = D.NIVEL_URGENCIA_ID_NIVEL_URGENCIA;

-- PROCEDIMIENTO: BUSCAR PACIENTE POR CORREO
DELIMITER $$
CREATE PROCEDURE SP_BUSCAR_PACIENTE_CORREO(IN P_CORREO VARCHAR(100))
BEGIN
  SELECT * FROM PACIENTE WHERE CORREO = P_CORREO;
END $$
DELIMITER ;

-- TRIGGER: ACTUALIZA LA VISTA CUANDO SE INSERTA UN TRIAGE
DELIMITER $$
CREATE TRIGGER TRG_TRIAGE_INSERT
AFTER INSERT ON TRIAGE
FOR EACH ROW
BEGIN
  UPDATE VISITA SET TRIAGE_ID_TRIAGE = NEW.ID_TRIAGE WHERE ID_VISITA = NEW.VISITA_ID_VISITA;
END $$
DELIMITER ;